#!/usr/bin/env python

import sys
from os import path
from pathlib import Path

if len(sys.argv) < 2:
    print("Expected day number", file=sys.stderr)
    sys.exit(1)

n = int(sys.argv[1])
here = Path(path.dirname(__file__))
day_path = here / "days" / f"day{n}"
day_path.mkdir(parents=True, exist_ok=True)


def mkfile(name, content=""):
    if (day_path / name).exists():
        return
    with open(day_path / name, "w+") as f:
        f.write(content)


for name in [
    "__init__.py",
    "part1.py",
    "part2.py",
    "test_part1.py",
    "test_part2.py",
    f"day{n}lib.py",
]:
    mkfile(name)
